image: docker:stable

services:
  - "docker:dind"

variables:
  # 1) Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: 'obj'
  # 2) Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  # 3) A relative path to the source code from project repository root.
  # NOTE: Please edit this path so it matches the structure of your project!
  SOURCE_CODE_PATH: '*/*/'

before_script:
  - docker info

build:
  stage: build

  before_script:
    - 'docker login -u gitlab-ci-token -p glpat-of76FyMAkjB46CRxVA9K ${CI_REGISTRY}'
  script:
    - 'docker build -f Soicheek/Soicheek/Dockerfile -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .'
    - 'docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest'
  after_script:
    - 'docker logout ${CI_REGISTRY}'

tests-DAL:
  stage: test
  script:
    - 'docker build -f Soicheek.DAL.Test/Dockerfile .'
  dependencies:
    - build

tests-BL:
  stage: test
  script:
    - 'docker build -f Soicheek.BL.Test/Dockerfile .'
  dependencies:
    - build

deploy:
  stage: deploy
  only:
    - main
  script:
    - 'docker stop soicheek && docker rm soicheek'
    - 'docker run --network nginx-proxy_default -d --restart=always --name soicheek ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest'
  environment: production
  dependencies:
    - build
    - tests-DAL
    - tests-BL
